
underlay:
    local:
        asn: 60022
    neighbors:
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60011
        peer_ip: 172.16.0.34
        local_ip: 172.16.0.35
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60012
        peer_ip: 172.16.0.38
        local_ip: 172.16.0.39
