
underlay:
    local:
        asn: 60024
    neighbors:
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60013
        peer_ip: 172.16.0.42
        local_ip: 172.16.0.43
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60014
        peer_ip: 172.16.0.46
        local_ip: 172.16.0.47
