---
- name: Create and apply configuration for Leaves QFX / L3
  hosts: leaf-qfx-l3
  connection: local
  gather_facts: no
  roles:
    - common
    - underlay-ebgp
    - overlay-evpn-qfx-l3
    - overlay-evpn-access
