---
- name: Create and apply configuration for Leaves QFX / L2
  hosts: leaf-qfx-l2
  connection: local
  gather_facts: no
  roles:
    - common
    - underlay-ebgp
    - overlay-evpn-qfx-l2
    - overlay-evpn-access
