
- name: Checking Netconf connectivity
  hosts: all
  connection: local
  gather_facts: no
  vars:
    ssh_timeout: 5
  tasks:
    - wait_for: host={{ junos_host }} port={{ netconf_port }} timeout={{ ssh_timeout }}
