
- name: Checking BGP Underlay/overlay status
  hosts: all
  connection: local
  gather_facts: no
  vars:
    credential:
      host: "{{ junos_host }}"
      port: "{{ netconf_port }}"
      username: "{{ ansible_ssh_user }}"
      password: "{{ ansible_ssh_pass }}"

  tasks:
    - name: "Collect BGP information"
      junos_command:
        commands:
          - show bgp summary
        provider: "{{ credential }}"
      register: bgp
    - name: "Check peer status"
      assert:
        that:
          - item['peer-state'] == 'Established'
      with_items: "{{ bgp.stdout[0]['bgp-information']['bgp-peer'] }} "
