---
- name: Create and apply configuration for Fabric
  hosts: fabric
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ebgp
    - build-config
