---
- name: Create and apply configuration for Spines / QFX
  hosts: spine-qfx
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  roles:
    - common
    - underlay-ebgp
    - overlay-evpn-qfx-l3
    - build-config
