---
- name: Create and apply configuration for Leaf QFX / L3
  hosts: leaf-qfx-l3
  connection: local
  gather_facts: no
  roles:
    - junos-system
    # - underlay-ebgp
    # - overlay-evpn-qfx-l3
    # - overlay-evpn-access
    - build-config
