- name: Execute commands on devices
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Check if directory cmd_output/ is present
      file: path=cmd_output/ state=directory
      run_once: true

    - name: "Execute show bgp summary"
      junos_cli: >
        host={{ junos_host }}
        port={{ netconf_port }}
        user={{ ansible_ssh_user }}
        passwd={{ ansible_ssh_pass }}
        format=text
        cli="show bgp summary"
        dest=cmd_output/{{inventory_hostname}}_show_bgp_summary.txt
        logfile=/tmp/changes.log
