---
- name: Create and apply configuration for Leaf QFX / L2
  hosts: leaf-qfx-l2
  connection: local
  gather_facts: no
  roles:
    - junos-system
    - underlay-ebgp
    - overlay-evpn-qfx-l2
    - overlay-evpn-access
    - build-config
