---
- name: Create and apply configuration for Spines / MX
  hosts: spine-mx
  connection: local
  gather_facts: no
  roles:
    - junos-system
    # - underlay-ebgp
    # - overlay-evpn-mx-l3
    - build-config
