underlay:
    local:
        asn: 60014
    neighbors:
## Fabric
      - interface: "{{ topo[inventory_hostname].port3.name }}"
        name: "{{ topo[inventory_hostname].port3.peer }}"
        asn: 60001
        peer_ip: 172.16.0.6
        local_ip: 172.16.0.7
      - interface: "{{ topo[inventory_hostname].port4.name }}"
        name: "{{ topo[inventory_hostname].port4.peer }}"
        asn: 60002
        peer_ip: 172.16.0.14
        local_ip: 172.16.0.15

## Leaf
      - interface: "{{ topo[inventory_hostname].port1.name }}"
        name: "{{ topo[inventory_hostname].port1.peer }}"
        asn: 60023
        peer_ip: 172.16.0.45
        local_ip: 172.16.0.44
      - interface: "{{ topo[inventory_hostname].port2.name }}"
        name: "{{ topo[inventory_hostname].port2.peer }}"
        asn: 60024
        peer_ip: 172.16.0.47
        local_ip: 172.16.0.46
